### ISSUE TITLE
Personas 404 errors

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/project_electron#22]
Broken links for:
Nashmia Khan
Paul Roberts
Beatriz Oliviera
Annette Johnson
Matthew Harris
Laura Kozlowski

**Comment by helrond** [comment]
@HaSistrunk are all these broken links in https://github.com/RockefellerArchiveCenter/project_electron/blob/master/README.md or are they in other places?

**Comment by HaSistrunk** [comment]
Just the README as far as I have seen.

**Comment by helrond** [comment]
Fixed by bf559e4be06bb7dcd2b466c1d4a725174fd524f7
