### ISSUE TITLE
Remove mention of md5 checksums from BagIt Spec and profile

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/project_electron#88]
## Is your feature request related to a problem? Please describe.
Aurora is now running on CentOS 8, which does not support md5 checksums for security reasons. 

## Describe the solution you'd like
Remove all mentions of md5 checksums from the RAC BagIt spec as well as the sample BagIt Profile.

**Comment by HaSistrunk** [comment]
There's no mention of md5 in the BagIt profile. Do we need to _exclude_ md5 in the profile, or leave it as is? https://gist.github.com/HaSistrunk/65d59e558c436b9d934d98fd8fb0f575

**Comment by helrond** [comment]
The [BagIt Profile Spec](https://bagit-profiles.github.io/bagit-profiles-specification/#implementation-details) has `Manifests-Required` and `Manifests-Allowed` keys which control what checksum algorithms are required and allowed respectively. Currently we don't use either of those keys, which means that any and all algorithms are allowed. I'm proposing we add an array to the `Manifests-Allowed` key which explicitly excludes `md5`.

**Comment by HaSistrunk** [comment]
Ok, that makes sense. I've made that update on the gist. `Manifests-Allowed` includes `sha256` and `sha512`.
